### ISSUE TITLE
Cannot load pokec dataset

### ISSUE THREAD

**Issue by Xi-yuanWang** [qitianwu/DIFFormer#7]
Hello. It seems that scipy cannot read the mat file of the pokec dataset. Could you please help me?

Traceback (most recent call last):
  File "/home/wangxiyuan/DIFFormer/node classification/main-batch.py", line 43, in <module>
    dataset = load_dataset(args.data_dir, args.dataset, args.sub_dataset)
  File "/home/wangxiyuan/DIFFormer/node classification/dataset.py", line 109, in load_dataset
    dataset = load_pokec_mat(data_dir)
  File "/home/wangxiyuan/DIFFormer/node classification/dataset.py", line 312, in load_pokec_mat
    fulldata = scipy.io.loadmat(f'{data_dir}pokec.mat')
  File "/home/wangxiyuan/miniconda3/lib/python3.10/site-packages/scipy/io/matlab/_mio.py", line 225, in loadmat
    MR, _ = mat_reader_factory(f, **kwargs)
  File "/home/wangxiyuan/miniconda3/lib/python3.10/site-packages/scipy/io/matlab/_mio.py", line 74, in mat_reader_factory
    mjv, mnv = _get_matfile_version(byte_stream)
  File "/home/wangxiyuan/miniconda3/lib/python3.10/site-packages/scipy/io/matlab/_miobase.py", line 251, in _get_matfile_version
    raise ValueError('Unknown mat file type, version %s, %s' % ret)
ValueError: Unknown mat file type, version 32, 99

**Comment by qitianwu** [comment]
Hi, have you followed the requirements.txt for installing the correct version of the scipy package

**Comment by Xi-yuanWang** [comment]
Sorry for my late reply. Yes. I use scipy 1.6.2. Could you please npy format data?

**Comment by qitianwu** [comment]
Sorry for the late reply, the original data of pokec is provided in the mat format. So I doubt the issue is caused by the mismatch of packages. Our dataloader follows the implementation 

https://github.com/CUAI/Non-Homophily-Benchmarks
